--- 
script: python tests.py
language: python
python: 
- "2.6"
- "2.7"
install: pip install -r requirements.txt --use-mirrors
env: 
  global: 
  - secure: |-
      ahgWHHRdu65OLx9QGXBve21/kzn1SG5kkMT041+cq+WL3H0A/Ne4DLof1vft
      j1fRxx79k4+FAASZCBIKbNJ+5j/IpUynzPiNNzZp8aRQbWeaypTpxb4ZWyNh
      rk4EZVLG2R7Wd9zEcA31RqtIvZWtSwVilFhUF7jJPB0yh0tNKmA=
  - secure: |-
      b+bvdHf6wkevs2yvgOectxeuHA4NVaUkXrhp7eI1poMHjw6/5XL7OuEIitKH
      4P7x5h7DxBcLb/l5vBN6JjYAUI64pO8bYQKjo8wmCSBnXyBOCMyNmlPVM4Ys
      x/jKllM57JuXU9l4BRYU9oU1q0amIDu0Pwppkzne6uy5cZHyxqs=
